server {
    listen 80;
    server_name localhost;

    # Serve static files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Serve JavaScript files with the correct MIME type
    location ~ \.js$ {
        add_header Content-Type application/javascript;
    }

    # Serve CSS files with the correct MIME type
    location ~ \.css$ {
        add_header Content-Type text/css;
    }

    # Error page configuration
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}