export const symbols = [

    // use it minimal - where api calls are limited 


    { symbol: 'AAPL', quantity: 10, name: 'Apple Inc.' }, // Apple Inc. (Technology)
    { symbol: 'MSFT', quantity: 5, name: 'Microsoft Corporation' }, // Microsoft Corporation (Technology)
    { symbol: 'GOOGL', quantity: 3, name: 'Alphabet Inc.' }, // Alphabet Inc. (Technology)
    { symbol: 'AMZN', quantity: 2, name: 'Amazon.com Inc.' }, // Amazon.com Inc. (Consumer Discretionary)
    { symbol: 'TSLA', quantity: 4, name: 'Tesla Inc.' }, // Tesla Inc. (Automotive)
    { symbol: 'META', quantity: 6, name: 'Meta Platforms Inc.' }, // Meta Platforms Inc. (Technology)
    { symbol: 'JNJ', quantity: 8, name: 'Johnson & Johnson' }, // Johnson & Johnson (Pharmaceuticals)
    { symbol: 'PFE', quantity: 7, name: 'Pfizer Inc.' }, // Pfizer Inc. (Pharmaceuticals)
    { symbol: 'WMT', quantity: 9, name: 'Walmart Inc.' }, // Walmart Inc. (Consumer Staples)
    { symbol: 'KO', quantity: 7, name: 'Coca-Cola Co.' }, // Coca-Cola Co. (Consumer Staples)
    // { symbol: 'NFX', quantity: 169, name: 'Newfield Exploration Co.' }, // Newfield Exploration Co. (Energy)
    // { symbol: 'RDS.A', quantity: 170, name: 'Royal Dutch Shell plc' }, // Royal Dutch Shell plc (Energy)
    // { symbol: 'BP', quantity: 171, name: 'BP plc' }, // BP plc (Energy)
    // { symbol: 'TOT', quantity: 172, name: 'TotalEnergies SE' }, // TotalEnergies SE (Energy)
    // { symbol: 'EQNR', quantity: 173, name: 'Equinor ASA' }, // Equinor ASA (Energy)
    // { symbol: 'ENI', quantity: 174, name: 'Eni SpA' }, // Eni SpA (Energy)
    // { symbol: 'REP', quantity: 175, name: 'Repsol SA' }, // Repsol SA (Energy)
    // { symbol: 'YPF', quantity: 176, name: 'YPF SA' }, // YPF SA (Energy)
    // { symbol: 'PBR', quantity: 177, name: 'Petróleo Brasileiro SA' }, // Petróleo Brasileiro SA (Energy)
    // { symbol: 'EC', quantity: 178, name: 'Ecopetrol SA' }, // Ecopetrol SA (Energy)
    // { symbol: 'CEO', quantity: 179, name: 'CNOOC Ltd.' }, // CNOOC Ltd. (Energy)
    // { symbol: 'PTR', quantity: 180, name: 'PetroChina Co. Ltd.' }, // PetroChina Co. Ltd. (Energy)
    // { symbol: 'SNP', quantity: 181, name: 'China Petroleum & Chemical Corp.' }, // China Petroleum & Chemical Corp. (Energy)
    // { symbol: 'SHI', quantity: 182, name: 'Sinopec Shanghai Petrochemical Co. Ltd.' }, // Sinopec Shanghai Petrochemical Co. Ltd. (Energy)
    // { symbol: 'HNP', quantity: 183, name: 'Huaneng Power International Inc.' }, // Huaneng Power International Inc. (Energy)
    // { symbol: 'CEA', quantity: 184, name: 'China Eastern Airlines Corp. Ltd.' }, // China Eastern Airlines Corp. Ltd. (Industrials)
    // { symbol: 'ZNH', quantity: 185, name: 'China Southern Airlines Co. Ltd.' }, // China Southern Airlines Co. Ltd. (Industrials)
    // { symbol: 'AIR', quantity: 186, name: 'AAR Corp.' }, // AAR Corp. (Industrials)
    // { symbol: 'BA', quantity: 187, name: 'Boeing Co.' }, // Boeing Co. (Industrials)
    // { symbol: 'GD', quantity: 188, name: 'General Dynamics Corp.' }, // General Dynamics Corp. (Industrials)
    // { symbol: 'LMT', quantity: 189, name: 'Lockheed Martin Corp.' }, // Lockheed Martin Corp. (Industrials)
    // { symbol: 'NOC', quantity: 190, name: 'Northrop Grumman Corp.' }, // Northrop Grumman Corp. (Industrials)
    // { symbol: 'RTX', quantity: 191, name: 'Raytheon Technologies Corp.' }, // Raytheon Technologies Corp. (Industrials)
    // { symbol: 'TXT', quantity: 192, name: 'Textron Inc.' }, // Textron Inc. (Industrials)
    // { symbol: 'HII', quantity: 193, name: 'Huntington Ingalls Industries Inc.' }, // Huntington Ingalls Industries Inc. (Industrials)
    // { symbol: 'HEI', quantity: 194, name: 'HEICO Corp.' }, // HEICO Corp. (Industrials)
    // { symbol: 'CW', quantity: 195, name: 'Curtiss-Wright Corp.' }, // Curtiss-Wright Corp. (Industrials)
    // { symbol: 'KAMN', quantity: 196, name: 'Kaman Corp.' }, // Kaman Corp. (Industrials)
    // { symbol: 'SPR', quantity: 197, name: 'Spirit AeroSystems Holdings Inc.' }, // Spirit AeroSystems Holdings Inc. (Industrials)
    // { symbol: 'TDG', quantity: 198, name: 'TransDigm Group Inc.' }, // TransDigm Group Inc. (Industrials)
    { symbol: 'HXL', quantity: 199, name: 'Hexcel Corp.' }, // Hexcel Corp. (Industrials)
    // { symbol: 'ATRO', quantity: 200, name: 'Astronics Corp.' }, // Astronics Corp. (Industrials)
  ];